create table if not exists public.radarmusic_analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_name text not null check (event_name in ('page_view', 'store_click')),
  release_slug text not null,
  session_id text not null,
  provider text,
  target_url text,
  referrer_origin text,
  viewport_bucket text not null default 'unknown' check (viewport_bucket in ('mobile', 'tablet', 'desktop', 'unknown'))
);

create index if not exists radarmusic_analytics_events_release_created_idx on public.radarmusic_analytics_events (release_slug, created_at desc);
create index if not exists radarmusic_analytics_events_release_event_idx on public.radarmusic_analytics_events (release_slug, event_name);

alter table public.radarmusic_analytics_events enable row level security;

-- Service-role ingestion and reporting only. Do not expose this table to anonymous clients.
revoke all on table public.radarmusic_analytics_events from anon, authenticated;
