create table if not exists public.radarmusic_notification_subscriptions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  owner_id uuid not null,
  release_slug text not null,
  channel text not null check (channel in ('email', 'sms')),
  destination text not null,
  unsubscribe_token text not null unique,
  enabled boolean not null default true,
  consent_at timestamptz not null default now(),
  unsubscribed_at timestamptz
);

create table if not exists public.radarmusic_notification_deliveries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  subscription_id bigint not null references public.radarmusic_notification_subscriptions(id) on delete cascade,
  event_name text not null,
  provider text
);

create index if not exists radarmusic_notification_subscriptions_release_idx on public.radarmusic_notification_subscriptions (release_slug, enabled);
create index if not exists radarmusic_notification_deliveries_window_idx on public.radarmusic_notification_deliveries (subscription_id, created_at desc);

alter table public.radarmusic_notification_subscriptions enable row level security;
alter table public.radarmusic_notification_deliveries enable row level security;
revoke all on table public.radarmusic_notification_subscriptions from anon, authenticated;
revoke all on table public.radarmusic_notification_deliveries from anon, authenticated;
